#!/usr/bin/env bash
# Cross-compile with zig cc (docs/investigations/launch.md). Each flavor produces:
#   X3DAudio1_7.dll  the agent, as an X3DAudio1_7 proxy (Gobi/Binaries/Win64; loads on Windows and Proton as is)
#   dwmapi.dll       the same agent as a dwmapi proxy (dev only, launch/install.sh --legacy; not shipped; Proton needs
#                    WINEDLLOVERRIDES="dwmapi=n,b")
#   xinput1_3.dll    Windows launch redirect for the game's root folder (skips the EAC bootstrapper); no dev code
# Flavors:
#   native/build.sh            dev build -> native/out/: TCP command server (127.0.0.1:47112), test commands,
#                              offline=1 sign-in automation (launch/install.sh, launch/multi.sh)
#   native/build.sh --release  player build -> native/out/release/ (defines B4B_RELEASE): none of the above; what
#                              launch/package.sh ships
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
zig="$here/../vendor/zig/zig"
mh="$here/../vendor/minhook"
flavor=dev out="$here/out" defs=()
for a in "$@"; do
  case "$a" in
    --release) flavor=release out="$here/out/release" defs=(-DB4B_RELEASE) ;;
    *) echo "usage: build.sh [--release]" >&2; exit 2 ;;
  esac
done
mkdir -p "$out"
# VERSION (repo root) -> generated header: B4B_VERSION "x.y.z", B4B_PROTOCOL n (host and clients must match)
version=$(sed -n 's/^version=//p' "$here/../VERSION") protocol=$(sed -n 's/^protocol=//p' "$here/../VERSION")
[[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$ && $protocol =~ ^[1-9][0-9]*$ ]] ||
  { echo "build.sh: bad VERSION (version=$version protocol=$protocol)" >&2; exit 1; }
gen="$here/out/gen"; mkdir -p "$gen"
printf '// generated by native/build.sh from VERSION; do not edit\n#define B4B_VERSION "%s"\n#define B4B_PROTOCOL %s\n' \
  "$version" "$protocol" > "$gen/b4bcoop_version.h.$$" && mv -f "$gen/b4bcoop_version.h.$$" "$gen/b4bcoop_version.h"
cc() { "$zig" cc -target x86_64-windows-gnu -shared -O2 -g0 -s -Wall -Wno-unused-function -I"$gen" "${defs[@]}" "$@"; }
# The overlay (#26) is C++ with Dear ImGui (vendor/imgui, tools/fetch-deps.sh): compiled once per flavor to objects.
# WIDL_EXPLICIT_AGGREGATE_RETURNS: MSVC's ABI for COM methods that return structs (mingw's d3d12.h).
im="$here/../vendor/imgui" obj="$out/obj"; mkdir -p "$obj"
cxx_obj() {   # cxx_obj <source> -> $obj/<name>.o (rebuilt when the source is newer)
  local o="$obj/$(basename "${1%.*}").o"
  if [[ ! -f $o || $1 -nt $o || $here/build.sh -nt $o || ( $1 == */overlay.cpp && -n $(find "$here/src" -name '*.h' -newer "$o") ) ]]; then
    "$zig" c++ -target x86_64-windows-gnu -c -O2 -g0 -std=c++17 -fno-exceptions -fno-rtti -Wall -Wno-unused-function -Wno-unused-but-set-variable \
      -DWIDL_EXPLICIT_AGGREGATE_RETURNS -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_DISABLE_DEMO_WINDOWS \
      -DIMGUI_DISABLE_DEFAULT_SHELL_FUNCTIONS -I"$im" -I"$im/backends" -I"$mh/include" -I"$here/src" -I"$gen" "${defs[@]}" "$1" -o "$o" ||
      { rm -f "$o"; return 1; }   # never link a stale object
  fi
  echo "$o"
}
cxx_objs=()
for f in "$im"/imgui.cpp "$im"/imgui_draw.cpp "$im"/imgui_tables.cpp "$im"/imgui_widgets.cpp "$im"/backends/imgui_impl_dx12.cpp \
         "$here"/src/overlay.cpp; do o=$(cxx_obj "$f") || exit 1; cxx_objs+=("$o"); done
agent() {   # agent <proxy name> <output file>
  cc -I"$mh/include" -I"$here/src" \
    "$here"/src/*.c "$here/proxy/$1.c" "$mh"/src/hook.c "$mh"/src/buffer.c "$mh"/src/trampoline.c "$mh"/src/hde/hde64.c \
    "${cxx_objs[@]}" "$here/proxy/$1.def" -lws2_32 -lc++ -o "$out/$2"
}
agent x3daudio1_7 X3DAudio1_7.dll
agent dwmapi dwmapi.dll
cc "$here/launcher/redirect.c" "$here/proxy/xinput1_3.c" "$here/proxy/xinput1_3.def" -o "$out/xinput1_3.dll"
rm -f "$out"/*.lib "$out"/*.pdb
echo "built $out/{X3DAudio1_7,dwmapi,xinput1_3}.dll ($flavor, b4bcoop $version protocol $protocol)"
