#include <windows.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "cmds.h"
#include "ue.h"
#include "log.h"
#include "netguard.h"
#include "b4bcoop_version.h"   // generated by native/build.sh from VERSION

void out_reset(Out *o) { o->len = 0; o->buf[0] = 0; }
void out_printf(Out *o, const char *fmt, ...) {
    if (o->len >= sizeof o->buf - 1) return;
    va_list ap; va_start(ap, fmt);
    int n = vsnprintf(o->buf + o->len, sizeof o->buf - o->len, fmt, ap);
    va_end(ap);
    if (n > 0) o->len += (size_t)n < sizeof o->buf - o->len ? (size_t)n : sizeof o->buf - o->len - 1;
}

static void fstring_from(FString *s, const char *utf8, wchar_t *storage, int cap) {
    int n = 0;
    for (; utf8[n] && n < cap - 1; n++) storage[n] = (wchar_t)(unsigned char)utf8[n];
    storage[n] = 0;
    s->data = storage; s->num = n + 1; s->max = cap;
}

#ifndef B4B_RELEASE
// ---- dev-only agent commands (TCP command server, main.c) ----
static char nb[512], pb[1024];
#define NAME(o) ((o) ? ue_obj_name((o), nb, sizeof nb) : "null")
#define PATH(o) ((o) ? ue_full_path((o), pb, sizeof pb) : "null")

static const char *class_of(UObject *o) { static char b[256]; return o ? ue_obj_name(U_CLASS(o), b, sizeof b) : "null"; }

static void cmd_status(Out *o) {
    UObject *w = ue_world();
    out_printf(o, "b4bcoop %s (protocol %d)%s host_ip=%d\n", coop_version(), coop_protocol(),
               coop_protocol() != B4B_PROTOCOL ? " [b4bcoop_protocol_override]" : "", coop_host_ip());
    out_printf(o, "objects: %d\n", ue_num_objects());
    out_printf(o, "engine: %s\n", PATH(ue_engine()));
    out_printf(o, "world: %s\n", PATH(w));
    if (!w) return;
    UObject *gi = ue_get_ptr(w, "OwningGameInstance");
    UObject *gm = ue_get_ptr(w, "AuthorityGameMode");
    UObject *gs = ue_get_ptr(w, "GameState");
    UObject *nd = ue_get_ptr(w, "NetDriver");
    out_printf(o, "gameinstance: %s (%s)\n", NAME(gi), class_of(gi));
    out_printf(o, "gamemode: %s (%s)\n", NAME(gm), class_of(gm));
    out_printf(o, "gamestate: %s\n", class_of(gs));
    out_printf(o, "localpc: %s\n", class_of(ue_local_pc()));
    steamnet_status(o);
    if (nd) {
        UObject *sc = ue_get_ptr(nd, "ServerConnection");
        TArray *cc = (TArray *)((char *)nd + ue_prop_offset(nd, "ClientConnections"));
        out_printf(o, "netdriver: %s (%s) server_conn=%s client_conns=%d\n", NAME(nd), class_of(nd), sc ? "yes" : "no", cc->num);
        for (int i = 0; i < cc->num; i++) out_printf(o, "  conn[%d]: %s\n", i, class_of(((UObject **)cc->data)[i]));
    } else out_printf(o, "netdriver: none (standalone)\n");
}
#endif  // !B4B_RELEASE

static int exec_console(const char *cmd) {
    static UClass *ksl; static UFunction *fn;
    if (!ksl) ksl = ue_find_class("KismetSystemLibrary");
    if (ksl && !fn) fn = ue_find_function(ksl, "ExecuteConsoleCommand");
    UObject *w = ue_world();
    if (!fn || !w) { LOG("exec: missing %s", fn ? "world" : "ExecuteConsoleCommand"); return -1; }
    static wchar_t wbuf[2048];
    struct { UObject *ctx; FString cmd; UObject *pc; } p = {0};
    p.ctx = w;
    fstring_from(&p.cmd, cmd, wbuf, 2048);
    p.pc = ue_local_pc();
    ue_process_event(UC_CDO(ksl), fn, &p);
    return 0;
}

void game_exec(const char *cmd) { LOG("exec: %s", cmd); exec_console(cmd); }

static void cmd_host(Out *o) {
    UObject *w = ue_world();
    if (!w) { out_printf(o, "no world\n"); return; }
    if (ue_is_listen_server(w)) { out_printf(o, "already hosting (%d client(s))\n", ue_num_clients(w)); return; }
    char pkg[512], cmd[600];
    ue_world_package(w, pkg, sizeof pkg);
    snprintf(cmd, sizeof cmd, "open %s?listen", pkg);
    game_exec(cmd);
    out_printf(o, "hosting: %s\n", cmd);
}

// ---- version / protocol (VERSION at the repo root -> b4bcoop_version.h) ----
// The protocol must match between host and clients: the client sends it with every join (URL option b4bcoop=), the
// host's login gate (admin.c) refuses another one, and a Steam Join Game checks the host's advertised one first.
static int protocol_override;   // dev builds: b4bcoop_protocol_override=N (test the mismatch path)
const char *coop_version(void) { return B4B_VERSION; }
int coop_protocol(void) { return protocol_override > 0 ? protocol_override : B4B_PROTOCOL; }

// The joiner's view: "Host runs b4bcoop 0.4.0 (protocol 2); you have 0.3.0 (protocol 1). Everyone needs the same
// version." host_ver/host_proto: the host's (empty proto = an older b4bcoop without a version check).
void coop_version_mismatch(char *buf, size_t n, const char *host_ver, const char *host_proto) {
    char host[80];
    if (host_proto && *host_proto)
        snprintf(host, sizeof host, "b4bcoop %s (protocol %s)", host_ver && *host_ver ? host_ver : "?", host_proto);
    else snprintf(host, sizeof host, "an older b4bcoop");
    snprintf(buf, n, "Host runs %s; you have %s (protocol %d). Everyone needs the same version.", host, coop_version(),
             coop_protocol());
}

// ---- IP joins and hosting (host_ip=1, advanced) ----
// Default (host_ip=0): joins go over Steam P2P only. The game's UDP sockets are bound to 127.0.0.1 (steamnet.c), so
// nothing is reachable from the network (no Windows Firewall prompt), and IP joins are refused except to this machine
// (local test copies: launch/multi.sh joins 127.0.0.1). host_ip=1 restores IP hosting and joining (port forwarding).
static int host_ip;
int coop_host_ip(void) { return host_ip; }
const char *coop_ip_join_off_msg(void) {
    return "Joining by IP address is off. Join through Steam instead: right-click your friend in the Steam friends "
           "list and choose Join Game, or accept their invite (or /join steam:<their SteamID64>).";
}
// "host[:port...]" is this machine (127.x.y.z or localhost)
int coop_is_loopback(const char *hostport) {
    char h[112]; size_t k = 0;
    while (hostport[k] && hostport[k] != ':' && hostport[k] != '?' && k < sizeof h - 1) { h[k] = hostport[k]; k++; }
    h[k] = 0;
    if (!_stricmp(h, "localhost")) return 1;
    unsigned a, b, c, d; char tail;
    return sscanf(h, "%u.%u.%u.%u%c", &a, &b, &c, &d, &tail) == 4 && a == 127 && b < 256 && c < 256 && d < 256;
}

// target: "ip[:port]" (default 7777) or "steam:<steamid64>" (Steam P2P, steamnet.c)
// Returns 0 when the join started, -1 for a bad target, -2 for a Steam target without Steam P2P, -3 for an IP join to
// another machine while host_ip=0.
static int cmd_join(const char *target, Out *o) {
    char url[300], cmd[400];
    int steam = steamnet_resolve_target(target, url, sizeof url);   // steam: -> a fake address carried over Steam P2P
    if (steam == -1) { LOG("join: bad target '%s'", target); out_printf(o, "bad join target: %s (ip[:port] or steam:<id64>)\n", target); return -1; }
    if (steam == -2) { out_printf(o, "cannot join %s: Steam P2P unavailable here (%s)\n", target, steamnet_last_error()); return -2; }
    if (!steam && !host_ip && !coop_is_loopback(url)) {
        LOG("join: refused IP join to %s (host_ip=0: Steam joins only)", url);
        out_printf(o, "%s\n", coop_ip_join_off_msg());
        return -3;
    }
    if (!steam) netguard_allow_host(url);   // a host given by name must still resolve
    // our version and protocol go with the login (checked by the host's PreLogin gate, admin.c) and every rejoin
    size_t ul = strlen(url);
    snprintf(url + ul, sizeof url - ul, "?b4bcoop=%d?b4bcoopver=%s", coop_protocol(), coop_version());
    snprintf(cmd, sizeof cmd, "open %s", url);
    travel_set_host(url);        // the follow/rejoin logic reopens exactly this URL (travel.c), same Steam peer
    game_exec(cmd);
    out_printf(o, "joining (%s): %s\n", steam ? "steam" : "ip", cmd);
    return 0;
}

// coop_join/coop_host from another thread: queued here, run on the next engine tick (pending_tick).
static DWORD game_tid;
static CRITICAL_SECTION pend_cs;
static INIT_ONCE pend_once = INIT_ONCE_STATIC_INIT;
static char pend_join[256];
static int pend_host;
static BOOL CALLBACK pend_init(PINIT_ONCE a, PVOID b, PVOID *c) { InitializeCriticalSection(&pend_cs); return TRUE; }
static void pend_lock(int on) {
    InitOnceExecuteOnce(&pend_once, pend_init, NULL, NULL);
    if (on) EnterCriticalSection(&pend_cs); else LeaveCriticalSection(&pend_cs);
}

static int off_game_thread(void) { return GetCurrentThreadId() != game_tid; }

static void pending_tick(void) {
    char j[256] = ""; int h;
    pend_lock(1);
    snprintf(j, sizeof j, "%s", pend_join); pend_join[0] = 0;
    h = pend_host; pend_host = 0;
    pend_lock(0);
    if (h) coop_host();
    if (j[0]) coop_join(j);
}

#ifndef B4B_RELEASE
static void cmd_exec(const char *cmd, Out *o) {
    out_printf(o, exec_console(cmd) ? "exec failed: %s\n" : "exec: %s\n", cmd);
}

static void cmd_find(const char *needle, int max, Out *o) {
    int n = ue_num_objects(), hits = 0;
    for (int i = 0; i < n && hits < max; i++) {
        UObject *x = ue_object_at(i);
        if (!x || !U_CLASS(x)) continue;
        ue_full_path(x, pb, sizeof pb);
        if (strstr(pb, needle)) { out_printf(o, "%p %s %s\n", (void *)x, class_of(x), pb); hits++; }
    }
    out_printf(o, "%d hit(s)\n", hits);
}

// call <Class> <Function> [cdo]: call a parameterless function (return value, if any, is printed raw)
static void cmd_call(const char *cls, const char *func, int on_cdo, Out *o) {
    UClass *c = ue_find_class(cls);
    if (!c) { out_printf(o, "no class %s\n", cls); return; }
    UObject *target = on_cdo ? UC_CDO(c) : ue_find_first_of(cls);
    UFunction *f = target ? ue_find_function(U_CLASS(target), func) : NULL;
    if (!f) { out_printf(o, "no %s on %s\n", target ? "function" : "instance", cls); return; }
    static uint8_t params[4096];
    memset(params, 0, sizeof params);
    ue_process_event(target, f, params);
    out_printf(o, "called %s.%s on %s; params[0..16]:", cls, func, PATH(target));
    for (int i = 0; i < 16 && i < UFN_PARMSSIZE(f); i++) out_printf(o, " %02x", params[i]);
    out_printf(o, "\n");
}

static void fstring_print(Out *o, FString *s) {
    for (int i = 0; s->data && i < s->num && s->data[i]; i++) out_printf(o, "%c", s->data[i] < 128 ? (char)s->data[i] : '?');
}

static void cmd_players(Out *o) {
    UObject *w = ue_world();
    UObject *gs = w ? ue_get_ptr(w, "GameState") : NULL;
    if (!gs) { out_printf(o, "no gamestate\n"); return; }
    TArray *pa = (TArray *)((char *)gs + ue_prop_offset(gs, "PlayerArray"));
    out_printf(o, "%d player state(s)\n", pa->num);
    for (int i = 0; i < pa->num; i++) {
        UObject *ps = ((UObject **)pa->data)[i];
        int32_t off = ue_prop_offset(ps, "PlayerNamePrivate");
        out_printf(o, "  [%d] %s name=", i, class_of(ps));
        if (off >= 0) fstring_print(o, (FString *)((char *)ps + off));
        UObject *pawn = ue_get_ptr(ps, "PawnPrivate");
        out_printf(o, " pawn=%s\n", class_of(pawn));
    }
}
#endif  // !B4B_RELEASE

// ---- auto host/join from b4bcoop.ini next to the DLL (no ini at all = the defaults) ----
//   (default)         -> host: whenever we're offline & standalone in Fort Hope, reopen it as a listen server that
//                        friends join over Steam P2P (Join Game, presence.c); off when join= is set
//   host=0|1          -> explicitly off / on
//   steam_p2p=0       -> no Steam P2P (steamnet.c)
//   host_ip=1         -> advanced: also host and join over plain IP/UDP (port forwarding; see coop_host_ip)
//   join=steam:<id64> -> whenever we're offline & standalone in Fort Hope, join that host (retry every 20s)
//   join=1.2.3.4[:p]  -> same over IP (host_ip=1, or 127.0.0.1 for local test copies)
//                        a comma-separated list is tried in turn (e.g. steam:<id64>,1.2.3.4:7777)
// A session join target from Steam (presence.c: Join Game, invite, launch command line) overrides both.
static int auto_host = -1;       // -1: not in the ini (default: host unless join= is set)
static int own_config;   // config came from B4B_COOP_CONFIG (per-instance), not the shared game-dir ini
static char session_join[300];   // from Steam, this session only
static int session_fails;        // join attempts since we were last connected
// Only the first instance on a machine auto-hosts from the shared ini (a second local copy shares it when testing).
int cmds_auto_host(void) {
#ifdef B4B_RELEASE
    return auto_host > 0 && !session_join[0];   // no local test copies in a player build
#else
    extern int g_agent_port;
    return auto_host > 0 && !session_join[0] && (own_config || g_agent_port == 47112);
#endif
}
static char auto_join[256];
static double auto_clock, auto_next;
int g_auto_offline;      // auto sign-in Offline (signin.c): armed by a Steam join; dev builds also by offline=1

// b4bcoop.ini next to the DLL, or B4B_COOP_CONFIG=<windows path> (per-instance config for several local copies
// sharing one game dir, see launch/multi.sh). Every config reader goes through this.
const char *cmds_config_path(void) {
    static char path[600];
    if (!path[0]) {
        extern char g_module_dir[];
        const char *env = getenv("B4B_COOP_CONFIG");
        if (env && *env) { snprintf(path, sizeof path, "%s", env); own_config = 1; }
        else snprintf(path, sizeof path, "%sb4bcoop.ini", g_module_dir);
    }
    return path;
}

// ---- b4bcoop.ini: shared reader, live reload, writer ----
// Every `name=value` line that is not a comment (';' or '#' first), name at the start of the line, spaces after '='
// skipped. fn gets each pair in file order; returns the number of pairs (-1: no file).
int cmds_ini_each(void (*fn)(const char *key, const char *val, void *ctx), void *ctx) {
    FILE *f = fopen(cmds_config_path(), "r");
    if (!f) return -1;
    char line[700];
    int n = 0;
    while (fgets(line, sizeof line, f)) {
        char *nl = strpbrk(line, "\r\n"); if (nl) *nl = 0;
        char *v = strchr(line, '='); if (!v || line[0] == '#' || line[0] == ';') continue;
        *v++ = 0;
        while (*v == ' ') v++;
        fn(line, v, ctx);
        n++;
    }
    fclose(f);
    return n;
}

// Live reload: the game thread checks the file's time stamp and size once a second; on a change every key whose value
// differs from the last read (or that was removed: val NULL = back to the default) goes to the modules' *_live
// handlers. A key no handler takes live is logged and named in chat ("restart the game"). Only changed keys are
// applied, so an unrelated edit doesn't undo what a chat command changed this session.
typedef struct { char key[40], val[600]; } IniKV;
typedef struct { IniKV kv[64]; int n; } IniSet;
static IniSet ini_last = {.n = -1};  // n -1: not read yet
static FILETIME ini_mtime;
static DWORD ini_size;
static int ini_exists;

static void ini_collect(const char *k, const char *v, void *ctx) {
    IniSet *t = ctx;
    if (strlen(k) >= sizeof t->kv[0].key) return;
    for (int i = 0; i < t->n; i++) if (!strcmp(t->kv[i].key, k)) { snprintf(t->kv[i].val, sizeof t->kv[i].val, "%s", v); return; }
    if (t->n >= 64) return;
    snprintf(t->kv[t->n].key, sizeof t->kv[0].key, "%s", k);
    snprintf(t->kv[t->n].val, sizeof t->kv[0].val, "%s", v);
    t->n++;
}
static void ini_read_all(IniSet *t) { t->n = 0; cmds_ini_each(ini_collect, t); }
static const IniKV *ini_find(const IniSet *t, const char *k) {
    for (int i = 0; i < t->n; i++) if (!strcmp(t->kv[i].key, k)) return &t->kv[i];
    return NULL;
}
static int ini_stat(FILETIME *mt, DWORD *sz) {
    WIN32_FILE_ATTRIBUTE_DATA a;
    if (!GetFileAttributesExA(cmds_config_path(), GetFileExInfoStandard, &a)) { memset(mt, 0, sizeof *mt); *sz = 0; return 0; }
    *mt = a.ftLastWriteTime; *sz = a.nFileSizeLow;
    return 1;
}
// the modules that can take a key while the game runs: 1 = applied
static int ini_apply_live(const char *key, const char *val) {
    return thirdperson_live(key, val) || flashlight_live(key, val) || joinpolicy_live(key, val) ||
           presence_live(key, val) || teamsize_live(key, val);
}
static void ini_snapshot(void) {
    ini_read_all(&ini_last);
    ini_exists = ini_stat(&ini_mtime, &ini_size);
}
void cmds_ini_poll(float dt) {
    static float acc;
    static IniSet now;
    if (ini_last.n < 0) { ini_snapshot(); return; }
    if ((acc += dt) < 1.f) return;
    acc = 0;
    FILETIME mt; DWORD sz;
    static FILETIME pend_mt; static DWORD pend_sz; static int pending;
    int ex = ini_stat(&mt, &sz);
    if (!ex || (!CompareFileTime(&mt, &ini_mtime) && sz == ini_size)) { pending = 0; return; }   // gone: keep settings
    // changed: apply once it has been stable for a poll (an editor may still be writing it)
    if (!pending || CompareFileTime(&mt, &pend_mt) || sz != pend_sz) { pending = 1; pend_mt = mt; pend_sz = sz; return; }
    pending = 0;
    ini_read_all(&now);
    char applied[300] = "", restart[300] = "";
    for (int pass = 0; pass < 2; pass++) {   // pass 0: new or changed keys, pass 1: removed keys
        const IniSet *from = pass ? &ini_last : &now, *other = pass ? &now : &ini_last;
        for (int i = 0; i < from->n; i++) {
            const IniKV *e = &from->kv[i], *o = ini_find(other, e->key);
            if (pass ? o != NULL : (o && !strcmp(o->val, e->val))) continue;
            const char *val = pass ? NULL : e->val;
            int ok = ini_apply_live(e->key, val);
            LOG("config: %s %s%s -> %s", e->key, pass ? "removed" : o ? "changed to " : "added: ", val ? val : "",
                ok ? "applied" : "needs a game restart");
            char *dst = ok ? applied : restart;
            size_t l = strlen(dst);
            if (l < 250) snprintf(dst + l, sizeof applied - l, "%s%s", l ? ", " : "", e->key);
        }
    }
    ini_last = now;
    ini_mtime = mt; ini_size = sz; ini_exists = ex;
    if (applied[0]) chat_local("b4bcoop.ini: applied %s", applied);
    if (restart[0]) chat_local("b4bcoop.ini: %s changed; restart the game for that", restart);
}

// Writer: set key=val in b4bcoop.ini, keeping everything else (comments, order, line endings). The first active
// `key=` line is replaced; else a commented `;key=`/`#key=` line is replaced by the active one (it keeps its place
// next to its explanation); else the line is appended. val NULL comments the active line out (back to the default).
// Written to <ini>.tmp and moved over the ini. The reload snapshot is updated, so the write doesn't come back as an
// edit. Returns 0 on success.
int cmds_ini_set(const char *key, const char *val) {
    const char *path = cmds_config_path();
    char tmp[620];
    snprintf(tmp, sizeof tmp, "%s.tmp", path);
    size_t kl = strlen(key);
    if (!kl || kl >= 40 || strpbrk(key, "=\r\n") || (val && strpbrk(val, "\r\n"))) return -1;
    FILE *f = fopen(path, "rb");
    char *buf = NULL;
    long len = 0;
    if (f) {
        fseek(f, 0, SEEK_END); len = ftell(f); fseek(f, 0, SEEK_SET);
        if (len < 0 || len > (1 << 20)) { fclose(f); return -1; }
        buf = malloc(len + 1);
        if (!buf || fread(buf, 1, len, f) != (size_t)len) { fclose(f); free(buf); return -1; }
        buf[len] = 0;
        fclose(f);
    }
    const char *eol = buf && strstr(buf, "\r\n") ? "\r\n" : buf ? "\n" : "\r\n";
    // find the active line, else the first commented one
    long act = -1, com = -1;
    for (long i = 0; buf && i < len; ) {
        long e = i;
        while (e < len && buf[e] != '\n') e++;
        const char *l = buf + i;
        if (!strncmp(l, key, kl) && l[kl] == '=' && act < 0) act = i;
        else if ((l[0] == ';' || l[0] == '#') && !strncmp(l + 1, key, kl) && l[kl + 1] == '=' && com < 0) com = i;
        i = e + 1;
    }
    long at = act >= 0 ? act : com;
    FILE *w = fopen(tmp, "wb");
    if (!w) { free(buf); return -1; }
    if (at >= 0) {
        long e = at;
        while (e < len && buf[e] != '\n' && buf[e] != '\r') e++;   // the line's end, before its CR/LF
        fwrite(buf, 1, at, w);
        if (val) fprintf(w, "%s=%s", key, val);
        else if (act >= 0) fprintf(w, ";%.*s", (int)(e - at), buf + at);   // comment the active line out
        else fwrite(buf + at, 1, e - at, w);                               // nothing active: leave the comment
        fwrite(buf + e, 1, len - e, w);
    } else {
        if (buf) fwrite(buf, 1, len, w);
        if (val) fprintf(w, "%s%s=%s%s", len && buf[len - 1] != '\n' ? eol : "", key, val, eol);
    }
    int bad = ferror(w);
    fclose(w);
    free(buf);
    if (bad || !MoveFileExA(tmp, path, MOVEFILE_REPLACE_EXISTING)) { DeleteFileA(tmp); return -1; }
    ini_snapshot();
    LOG("config: wrote %s%s%s", key, val ? "=" : " (commented out)", val ? val : "");
    return 0;
}

// Hotkeys (flashlight_key, thirdperson_key): a letter/digit (0 = the 0 key), or a VK code like
// 0x4C; off, none or empty = no key.
int cmds_parse_key(const char *v) {
    while (*v == ' ') v++;
    if (!*v || !_stricmp(v, "off") || !_stricmp(v, "none")) return 0;
    if (!v[1] && ((v[0] >= 'a' && v[0] <= 'z') || (v[0] >= 'A' && v[0] <= 'Z') || (v[0] >= '0' && v[0] <= '9')))
        return (v[0] >= 'a' && v[0] <= 'z') ? v[0] - 32 : v[0];
    return (int)strtol(v, NULL, 0);
}

// Hotkeys only count while the game window has focus.
int cmds_game_focused(void) {
    DWORD pid = 0;
    HWND w = GetForegroundWindow();
    if (w) GetWindowThreadProcessId(w, &pid);
    return pid == GetCurrentProcessId();
}

// Hotkey state through the game's own input (PlayerController.IsInputKeyDown): a key typed into the chat box or a
// menu never reaches it, and nothing depends on the window's focus or on GetAsyncKeyState, which under Wine can report
// a stale key right after the window is raised (thirdperson_key fired once by itself). Keys without an FKey name
// here, or no PlayerController yet, fall back to GetAsyncKeyState while the game window is in front.
static const char *vk_key_name(int vk, char *b, size_t n) {
    static const char *digits[] = {"Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"};
    static const struct { int vk; const char *name; } other[] = {
        {0xC0, "Tilde"}, {VK_TAB, "Tab"}, {VK_CAPITAL, "CapsLock"}, {VK_INSERT, "Insert"}, {VK_DELETE, "Delete"},
        {VK_HOME, "Home"}, {VK_END, "End"}, {VK_PRIOR, "PageUp"}, {VK_NEXT, "PageDown"}, {VK_MBUTTON, "MiddleMouseButton"},
        {VK_XBUTTON1, "ThumbMouseButton"}, {VK_XBUTTON2, "ThumbMouseButton2"}, {VK_BACK, "BackSpace"}, {VK_PAUSE, "Pause"}};
    if (vk >= 'A' && vk <= 'Z') { snprintf(b, n, "%c", vk); return b; }
    if (vk >= '0' && vk <= '9') return digits[vk - '0'];
    if (vk >= VK_F1 && vk <= VK_F12) { snprintf(b, n, "F%d", vk - VK_F1 + 1); return b; }
    if (vk >= VK_NUMPAD0 && vk <= VK_NUMPAD9) { snprintf(b, n, "NumPad%s", digits[vk - VK_NUMPAD0]); return b; }
    for (size_t i = 0; i < sizeof other / sizeof *other; i++) if (other[i].vk == vk) return other[i].name;
    return NULL;
}
typedef FName *(*CmdsFNameCtorFn)(FName *self, const wchar_t *name, int find_type);
int cmds_hotkey_down(int vk) {
    static struct { int vk; FName name; } names[8];
    static int n_names;
    static UFunction *fn; static int32_t o_key = -1, o_ret = -1, psize;
    UObject *pc = ue_local_pc();
    char nb[16];
    const char *kn = vk_key_name(vk, nb, sizeof nb);
    if (pc && kn && !fn) {
        UClass *c = ue_find_class("PlayerController");
        fn = c ? ue_find_function(c, "IsInputKeyDown") : NULL;
        FField *k = fn ? ue_find_prop((UStruct *)fn, "Key") : NULL, *r = fn ? ue_find_prop((UStruct *)fn, "ReturnValue") : NULL;
        if (k && r && UFN_PARMSSIZE(fn) <= 64) { o_key = FP_OFFSET(k); o_ret = FP_OFFSET(r); psize = UFN_PARMSSIZE(fn); }
    }
    if (pc && kn && o_key >= 0) {
        int i = 0;
        while (i < n_names && names[i].vk != vk) i++;
        if (i == n_names) {
            if (n_names == 8) n_names = i = 0;
            wchar_t w[16];
            for (int j = 0; j < 16; j++) if (!(w[j] = (wchar_t)kn[j])) break;
            w[15] = 0;
            memset(&names[i].name, 0, sizeof names[i].name);
            ((CmdsFNameCtorFn)VA(0x1424BC8E0ull))(&names[i].name, w, 1 /*FNAME_Add*/);   // FName::FName(TCHAR*)
            names[i].vk = vk;
            n_names++;
        }
        uint8_t p[64];
        memset(p, 0, psize);
        *(FName *)(p + o_key) = names[i].name;   // FKey {FName KeyName, TSharedPtr<FKeyDetails>}: looked up by name
        ue_process_event(pc, fn, p);
        return p[o_ret] != 0;
    }
    return (GetAsyncKeyState(vk) & 0x8000) && cmds_game_focused();
}

// join= without host_ip=1: drop IP targets on other machines (they would only be refused), tell the player once.
static void filter_ini_join(void) {
    if (host_ip || !auto_join[0]) return;
    char list[256], kept[256] = "", dropped[256] = "";
    snprintf(list, sizeof list, "%s", auto_join);
    for (char *t = strtok(list, ","); t; t = strtok(NULL, ",")) {
        while (*t == ' ') t++;
        if (!*t) continue;
        int ok = !_strnicmp(t, "steam:", 6) || !_strnicmp(t, "steam.", 6) || coop_is_loopback(t);
        char *dst = ok ? kept : dropped;
        size_t l = strlen(dst);
        snprintf(dst + l, 256 - l, "%s%s", l ? "," : "", t);
    }
    if (!dropped[0]) return;
    LOG("config: join=%s ignored (host_ip=0: IP joins are off, Steam joins only)", dropped);
    snprintf(auto_join, sizeof auto_join, "%s", kept);
    chat_local_later(coop_ip_join_off_msg());
}

static void load_config(void) {
    const char *path = cmds_config_path();
    FILE *f = fopen(path, "r");
    char line[300];
    while (f && fgets(line, sizeof line, f)) {
        char *nl = strpbrk(line, "\r\n"); if (nl) *nl = 0;
        char *v = strchr(line, '='); if (!v || line[0] == '#' || line[0] == ';') continue;
        *v++ = 0;
        while (*v == ' ') v++;
        if (!strcmp(line, "host")) auto_host = atoi(v) != 0;
        else if (!strcmp(line, "join") && *v) snprintf(auto_join, sizeof auto_join, "%s", v);
        else if (!strcmp(line, "host_ip")) host_ip = atoi(v) != 0;
#ifndef B4B_RELEASE
        else if (!strcmp(line, "offline")) g_auto_offline = atoi(v);   // unattended tests (launch/multi.sh)
        else if (!strcmp(line, "b4bcoop_protocol_override")) protocol_override = atoi(v);   // fake a version mismatch
#endif
        else if (!joinpolicy_config(line, v)) steamnet_config(line, v);
    }
    if (f) fclose(f);
    filter_ini_join();
    int dflt = auto_host < 0;
    if (dflt) auto_host = auto_join[0] ? 0 : 1;   // hosting is on by default; join= means this copy joins instead
    LOG("config: %s%s host=%d%s join=%s host_ip=%d offline=%d", path, f ? "" : " (not found: defaults)", auto_host,
        dflt ? " (default)" : "", auto_join[0] ? auto_join : "-", host_ip, g_auto_offline);
#ifndef B4B_RELEASE
    if (protocol_override) LOG("config: b4bcoop_protocol_override=%d (dev): claiming protocol %d", protocol_override, coop_protocol());
#endif
    if (host_ip) LOG("config: host_ip=1 (advanced): game UDP socket open to the network, IP joins allowed");
}

// Client: the host said "Server full." (no free survivor slot, slotguard.c): retry less often, since each attempt
// reloads the camp and shows the game's "session is full" popup.
void cmds_auto_join_backoff(double seconds) {
    if (!auto_join[0] || auto_next >= auto_clock + seconds - 1) return;
    auto_next = auto_clock + seconds;
    LOG("auto: the host refused the join, next attempt in %.0fs", seconds);
}

// ---- join / host / leave entry points (chat commands, Steam invites, future in-game UI) ----
// coop_join: "ip[:port]" joins over IP, "steam:<id64>" over Steam P2P (steamnet.c). Any thread: off the game
// thread the request is queued for the next engine tick. Callers on the game thread that need to know whether an
// attempt started compare g_travel_calls (travel.c) around it (a Steam target without Steam P2P starts nothing).
void coop_join(const char *target) {
    static Out scratch;
    while (target && *target == ' ') target++;
    if (!target || !*target) return;
    if (off_game_thread()) { pend_lock(1); snprintf(pend_join, sizeof pend_join, "%s", target); pend_lock(0); return; }
    out_reset(&scratch);
    int r = cmd_join(target, &scratch);
    if (r == -1) chat_local("bad join target %s, use /join steam:<id64>", target);
    if (r == -2) chat_local("Steam P2P is not available here (%s)%s", steamnet_last_error(), host_ip ? ", use /join <ip[:port]>" : "");
    if (r == -3) chat_local("%s", coop_ip_join_off_msg());
}

// coop_host: host the offline camp we are in (and keep hosting it after missions, like host=1). Any thread.
// The host takes Steam P2P joins (unless steam_p2p=0), and with host_ip=1 UDP joins from the network too.
void coop_host(void) {
    static Out scratch;
    if (off_game_thread()) { pend_lock(1); pend_host = 1; pend_lock(0); return; }
    auto_host = 1;
    own_config = 1;
    out_reset(&scratch);
    cmd_host(&scratch);
}

// coop_leave (client): drop the connection and go back to our own offline camp; no auto-rejoin afterwards.
void coop_leave(void) {
    cmds_auto_join_stop();
    if (session_join[0]) cmds_set_session_join(NULL);   // also drop a Steam Join Game target, or we'd rejoin in ~20s
    travel_set_host("");
    game_exec("disconnect");
}

void cmds_auto_join_stop(void) {
    if (auto_join[0]) LOG("auto: join %s stopped", auto_join);
    auto_join[0] = 0;
}

void cmds_set_session_join(const char *targets) {
    snprintf(session_join, sizeof session_join, "%s", targets ? targets : "");
    session_fails = 0;
    auto_next = auto_clock;
    LOG("auto: session join target %s", session_join[0] ? session_join : "cleared");
}
const char *cmds_session_join(void) { return session_join; }

// One join attempt: the next alternative of a comma-separated target list. An alternative that starts no travel
// (e.g. steam: without the P2P transport) is skipped at once.
static void join_next(const char *targets) {
    static int alt;
    char list[300], *alts[4];
    int n = 0;
    snprintf(list, sizeof list, "%s", targets);
    for (char *t = list; t && *t && n < 4;) {
        char *c = strchr(t, ',');
        if (c) *c++ = 0;
        while (*t == ' ') t++;
        if (*t) alts[n++] = t;
        t = c;
    }
    extern int g_travel_calls;
    for (int k = 0; k < n; k++) {
        const char *t = alts[alt++ % n];
        int before = g_travel_calls;
        LOG("auto: joining %s", t);
        coop_join(t);
        if (g_travel_calls != before) return;
        LOG("auto: %s started no connection, trying the next target", t);
    }
}

// Join the session target right away, from wherever we are (a Steam Join Game while hosting or in a session).
void cmds_join_now(void) {
    if (!session_join[0]) return;
    join_next(session_join);
    auto_next = auto_clock + 20;
}

static void auto_tick(float dt) {
    auto_clock += dt;
    const char *join = session_join[0] ? session_join : auto_join;
    if ((!cmds_auto_host() && !join[0]) || auto_clock < auto_next) return;
    auto_next = auto_clock + 2;
    UObject *w = ue_world();
    UObject *nd = w ? ue_get_ptr(w, "NetDriver") : NULL;
    int connected = nd && ue_get_ptr(nd, "ServerConnection");
    if (connected) session_fails = 0;
    // A Steam join may leave our own empty camp (host=1 opened even the title's Fort Hope with ?listen)
    int empty_host = session_join[0] && nd && !connected && ue_num_clients(w) == 0;
    if (!w || (nd && !empty_host)) return;                     // already hosting or connected
    char pkg[256]; ue_world_package(w, pkg, sizeof pkg);
    if (!strstr(pkg, "FortHope")) return;                      // only act from the offline camp
    if (!ue_local_pc()) return;                                // still loading
    if (session_join[0] && signin_pending()) return;   // Steam join: sign in (Offline) first
    static Out scratch;
    out_reset(&scratch);
    if (cmds_auto_host()) { LOG("auto: hosting"); cmd_host(&scratch); auto_next = auto_clock + 30; }
    else if (session_join[0] && ++session_fails > 6) {         // Steam target: the host is gone; back to the ini
        LOG("auto: no connection to %s after 6 attempts, giving up", session_join);
        cmds_set_session_join(NULL);
    }
    else { join_next(join); auto_next = auto_clock + 20; }
}

void cmds_init(void) { load_config(); }
static void set_float(UObject *o, const char *prop, float v) {
    int32_t off = o ? ue_prop_offset(o, prop) : -1;
    if (off >= 0) { *(float *)((char *)o + off) = v; }
}

// Raise net timeouts on the driver class defaults so slow (Proton, first-run shader) map loads don't
// drop clients mid-travel. Retail values are tuned for dedicated servers.
static void tune_net_defaults(void) {
    const char *classes[] = {"NetDriver", "IpNetDriver", "PacketRelayNetDriver"};
    for (int i = 0; i < 3; i++) {
        UClass *c = ue_find_class(classes[i]);
        if (!c || !UC_CDO(c)) continue;
        set_float(UC_CDO(c), "InitialConnectTimeout", 180.f);
        set_float(UC_CDO(c), "ConnectionTimeout", 90.f);
        LOG("net: tuned %s defaults", classes[i]);
    }
}

void cmds_tick(float dt) {
    static int tuned;
    game_tid = GetCurrentThreadId();
    if (!tuned) { tuned = 1; tune_net_defaults(); }
    pending_tick();
    travel_tick(dt);
    auto_tick(dt);
    flashlight_tick(dt);
    signin_tick(dt);
    teamsize_tick(dt);
    slotguard_tick(dt);
    chat_tick(dt);
    admin_tick(dt);
    presence_tick(dt);
    steamnet_tick(dt);
    joinpolicy_tick(dt);
    rewardguard_tick(dt);
    cheats_tick(dt);
    thirdperson_tick(dt);
    cmds_ini_poll(dt);
}

#ifndef B4B_RELEASE
void cmds_run(char *line, Out *o) {
    char *verb = strtok(line, " ");
    char *rest = strtok(NULL, "");
    if (!verb) { out_printf(o, "empty\n"); return; }
    if (!strcmp(verb, "ping")) out_printf(o, "pong\n");
    else if (!strcmp(verb, "status")) cmd_status(o);
    else if (!strcmp(verb, "players")) cmd_players(o);
    else if (!strcmp(verb, "host")) cmd_host(o);
    else if (!strcmp(verb, "flashlight")) cmd_flashlight(rest, o);
    else if (!strcmp(verb, "peek") && rest) {
        char *a = strtok(rest, " "), *l = strtok(NULL, " ");
        unsigned char *p = (unsigned char *)(uintptr_t)strtoull(a, NULL, 16);
        int n = l ? atoi(l) : 64;
        for (int i = 0; i < n; i++) out_printf(o, "%02x%s", p[i], (i % 16 == 15) ? "\n" : " ");
        out_printf(o, "\n");
    }
    else if (!strcmp(verb, "join") && rest) cmd_join(rest, o);   // same path as coop_join()
    else if (!strcmp(verb, "leave")) { coop_leave(); out_printf(o, "leaving\n"); }
    else if (!strcmp(verb, "exec") && rest) cmd_exec(rest, o);
    else if (!strcmp(verb, "netguard")) netguard_cmd(rest, o);
    else if (!strcmp(verb, "ini")) {   // dev: `ini` (last read), `ini set <key> <value>`, `ini unset <key>`
        char *a = rest ? strtok(rest, " ") : NULL, *k = a ? strtok(NULL, " ") : NULL, *v = k ? strtok(NULL, "") : NULL;
        if (a && k && (!strcmp(a, "set") && v ? 1 : !strcmp(a, "unset")))
            out_printf(o, "%s\n", cmds_ini_set(k, !strcmp(a, "set") ? v : NULL) ? "write failed" : "written");
        out_printf(o, "%s:\n", cmds_config_path());
        for (int i = 0; i < ini_last.n; i++) out_printf(o, "  %s=%s\n", ini_last.kv[i].key, ini_last.kv[i].val);
    }
    else if (!strcmp(verb, "find") && rest) {
        char *needle = strtok(rest, " "), *m = strtok(NULL, " ");
        cmd_find(needle, m ? atoi(m) : 50, o);
    } else if (!strcmp(verb, "call") && rest) {
        char *c = strtok(rest, " "), *f = strtok(NULL, " "), *cdo = strtok(NULL, " ");
        if (c && f) cmd_call(c, f, cdo && !strcmp(cdo, "cdo"), o); else out_printf(o, "usage: call <Class> <Func> [cdo]\n");
    } else if (!steamnet_cmd(verb, rest, o) && !testing_cmd(verb, rest, o) && !teamsize_cmd(verb, rest, o) && !lineup_cmd(verb, rest, o) &&
               !slotguard_cmd(verb, rest, o) && !chat_cmd(verb, rest, o) && !admin_cmd(verb, rest, o) &&
               !presence_cmd(verb, rest, o) && !rewardguard_cmd(verb, rest, o) && !joinpolicy_cmd(verb, rest, o) &&
               !cheats_cmd(verb, rest, o) && !thirdperson_cmd(verb, rest, o))
        out_printf(o, "unknown command: %s\n", verb);
}
#endif  // !B4B_RELEASE
