// GENERATED by tools/gen-proxy.py -- do not edit.
// dwmapi.dll proxy: re-exports all 119 exports of the real system dwmapi (ordinals in native/dwmapi.def).
// Each export is `jmp *slot`; a slot starts at a resolver thunk that looks up the real function on first call
// (by name, or by ordinal for unnamed exports), so nothing is loaded under the loader lock.
#include <windows.h>

#define NPROXY 119
static const char *const names[NPROXY] = {
    "DwmpDxGetWindowSharedSurface",  // @100
    "DwmpDxUpdateWindowSharedSurface",  // @101
    "DwmEnableComposition",  // @102
    0,  // @103
    0,  // @104
    0,  // @105
    0,  // @106
    0,  // @107
    0,  // @108
    0,  // @109
    0,  // @110
    "DllCanUnloadNow",  // @111
    0,  // @112
    0,  // @113
    0,  // @114
    "DllGetClassObject",  // @115
    "DwmAttachMilContent",  // @116
    "DwmDefWindowProc",  // @117
    "DwmDetachMilContent",  // @118
    "DwmEnableBlurBehindWindow",  // @119
    "DwmEnableMMCSS",  // @120
    "DwmExtendFrameIntoClientArea",  // @121
    "DwmFlush",  // @122
    "DwmGetColorizationColor",  // @123
    0,  // @124
    "DwmGetCompositionTimingInfo",  // @125
    "DwmGetGraphicsStreamClient",  // @126
    "DwmpGetColorizationParameters",  // @127
    "DwmpDxgiIsThreadDesktopComposited",  // @128
    "DwmGetGraphicsStreamTransformHint",  // @129
    "DwmGetTransportAttributes",  // @130
    "DwmpSetColorizationParameters",  // @131
    0,  // @132
    "DwmGetUnmetTabRequirements",  // @133
    "DwmGetWindowAttribute",  // @134
    "DwmpRenderFlick",  // @135
    "DwmpAllocateSecurityDescriptor",  // @136
    "DwmpFreeSecurityDescriptor",  // @137
    0,  // @138
    0,  // @139
    0,  // @140
    0,  // @141
    0,  // @142
    "DwmpEnableDDASupport",  // @143
    0,  // @144
    0,  // @145
    "DwmInvalidateIconicBitmaps",  // @146
    0,  // @147
    0,  // @148
    "DwmIsCompositionEnabled",  // @149
    0,  // @150
    0,  // @151
    0,  // @152
    0,  // @153
    0,  // @154
    0,  // @155
    "DwmTetherTextContact",  // @156
    0,  // @157
    0,  // @158
    0,  // @159
    0,  // @160
    0,  // @161
    0,  // @162
    0,  // @163
    0,  // @164
    0,  // @165
    0,  // @166
    0,  // @167
    0,  // @168
    0,  // @169
    0,  // @170
    0,  // @171
    0,  // @172
    0,  // @173
    0,  // @174
    0,  // @175
    0,  // @176
    0,  // @177
    0,  // @178
    0,  // @179
    0,  // @180
    0,  // @181
    0,  // @182
    "DwmpUpdateProxyWindowForCapture",  // @183
    0,  // @184
    0,  // @185
    0,  // @186
    0,  // @187
    0,  // @188
    0,  // @189
    0,  // @190
    0,  // @191
    0,  // @192
    0,  // @193
    0,  // @194
    0,  // @195
    0,  // @196
    0,  // @197
    0,  // @198
    0,  // @199
    0,  // @200
    0,  // @201
    0,  // @202
    0,  // @203
    0,  // @204
    "DwmModifyPreviousDxFrameDuration",  // @205
    "DwmQueryThumbnailSourceSize",  // @206
    "DwmRegisterThumbnail",  // @207
    "DwmRenderGesture",  // @208
    "DwmSetDxFrameDuration",  // @209
    "DwmSetIconicLivePreviewBitmap",  // @210
    "DwmSetIconicThumbnail",  // @211
    "DwmSetPresentParameters",  // @212
    "DwmSetWindowAttribute",  // @213
    "DwmShowContact",  // @214
    "DwmTetherContact",  // @215
    "DwmTransitionOwnedWindow",  // @216
    "DwmUnregisterThumbnail",  // @217
    "DwmUpdateThumbnailProperties",  // @218
};
static const unsigned short ords[NPROXY] = {
    100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218
};
extern void *b4b_dwm_slots[NPROXY];

static HMODULE real;
static HRESULT WINAPI not_impl(void) { return E_NOTIMPL; }

void *b4b_dwm_resolve(unsigned i) {
    if (!real) {
        wchar_t path[MAX_PATH];
        GetSystemDirectoryW(path, MAX_PATH);
        lstrcatW(path, L"\\dwmapi.dll");
        real = LoadLibraryW(path);
    }
    void *f = real ? (void *)GetProcAddress(real, names[i] ? names[i] : MAKEINTRESOURCEA(ords[i])) : 0;
    if (!f) f = (void *)not_impl;
    b4b_dwm_slots[i] = f;
    return f;
}

// Resolver entry: eax = slot index. Preserves the Win64 argument registers, then tail-jumps to the target.
__asm__(
    ".text\n"
    "b4b_dwm_common:\n"
    "  push %rcx\n  push %rdx\n  push %r8\n  push %r9\n"
    "  sub $0x68, %rsp\n"
    "  movdqu %xmm0, 0x20(%rsp)\n  movdqu %xmm1, 0x30(%rsp)\n"
    "  movdqu %xmm2, 0x40(%rsp)\n  movdqu %xmm3, 0x50(%rsp)\n"
    "  mov %eax, %ecx\n"
    "  call b4b_dwm_resolve\n"
    "  movdqu 0x20(%rsp), %xmm0\n  movdqu 0x30(%rsp), %xmm1\n"
    "  movdqu 0x40(%rsp), %xmm2\n  movdqu 0x50(%rsp), %xmm3\n"
    "  add $0x68, %rsp\n"
    "  pop %r9\n  pop %r8\n  pop %rdx\n  pop %rcx\n"
    "  jmp *%rax\n"
    ".globl b4b_dwm_100\nb4b_dwm_100: jmp *b4b_dwm_slots+0(%rip)\n"
    "b4b_dwm_r100: mov $0, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_101\nb4b_dwm_101: jmp *b4b_dwm_slots+8(%rip)\n"
    "b4b_dwm_r101: mov $1, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_102\nb4b_dwm_102: jmp *b4b_dwm_slots+16(%rip)\n"
    "b4b_dwm_r102: mov $2, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_103\nb4b_dwm_103: jmp *b4b_dwm_slots+24(%rip)\n"
    "b4b_dwm_r103: mov $3, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_104\nb4b_dwm_104: jmp *b4b_dwm_slots+32(%rip)\n"
    "b4b_dwm_r104: mov $4, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_105\nb4b_dwm_105: jmp *b4b_dwm_slots+40(%rip)\n"
    "b4b_dwm_r105: mov $5, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_106\nb4b_dwm_106: jmp *b4b_dwm_slots+48(%rip)\n"
    "b4b_dwm_r106: mov $6, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_107\nb4b_dwm_107: jmp *b4b_dwm_slots+56(%rip)\n"
    "b4b_dwm_r107: mov $7, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_108\nb4b_dwm_108: jmp *b4b_dwm_slots+64(%rip)\n"
    "b4b_dwm_r108: mov $8, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_109\nb4b_dwm_109: jmp *b4b_dwm_slots+72(%rip)\n"
    "b4b_dwm_r109: mov $9, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_110\nb4b_dwm_110: jmp *b4b_dwm_slots+80(%rip)\n"
    "b4b_dwm_r110: mov $10, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_111\nb4b_dwm_111: jmp *b4b_dwm_slots+88(%rip)\n"
    "b4b_dwm_r111: mov $11, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_112\nb4b_dwm_112: jmp *b4b_dwm_slots+96(%rip)\n"
    "b4b_dwm_r112: mov $12, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_113\nb4b_dwm_113: jmp *b4b_dwm_slots+104(%rip)\n"
    "b4b_dwm_r113: mov $13, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_114\nb4b_dwm_114: jmp *b4b_dwm_slots+112(%rip)\n"
    "b4b_dwm_r114: mov $14, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_115\nb4b_dwm_115: jmp *b4b_dwm_slots+120(%rip)\n"
    "b4b_dwm_r115: mov $15, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_116\nb4b_dwm_116: jmp *b4b_dwm_slots+128(%rip)\n"
    "b4b_dwm_r116: mov $16, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_117\nb4b_dwm_117: jmp *b4b_dwm_slots+136(%rip)\n"
    "b4b_dwm_r117: mov $17, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_118\nb4b_dwm_118: jmp *b4b_dwm_slots+144(%rip)\n"
    "b4b_dwm_r118: mov $18, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_119\nb4b_dwm_119: jmp *b4b_dwm_slots+152(%rip)\n"
    "b4b_dwm_r119: mov $19, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_120\nb4b_dwm_120: jmp *b4b_dwm_slots+160(%rip)\n"
    "b4b_dwm_r120: mov $20, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_121\nb4b_dwm_121: jmp *b4b_dwm_slots+168(%rip)\n"
    "b4b_dwm_r121: mov $21, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_122\nb4b_dwm_122: jmp *b4b_dwm_slots+176(%rip)\n"
    "b4b_dwm_r122: mov $22, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_123\nb4b_dwm_123: jmp *b4b_dwm_slots+184(%rip)\n"
    "b4b_dwm_r123: mov $23, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_124\nb4b_dwm_124: jmp *b4b_dwm_slots+192(%rip)\n"
    "b4b_dwm_r124: mov $24, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_125\nb4b_dwm_125: jmp *b4b_dwm_slots+200(%rip)\n"
    "b4b_dwm_r125: mov $25, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_126\nb4b_dwm_126: jmp *b4b_dwm_slots+208(%rip)\n"
    "b4b_dwm_r126: mov $26, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_127\nb4b_dwm_127: jmp *b4b_dwm_slots+216(%rip)\n"
    "b4b_dwm_r127: mov $27, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_128\nb4b_dwm_128: jmp *b4b_dwm_slots+224(%rip)\n"
    "b4b_dwm_r128: mov $28, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_129\nb4b_dwm_129: jmp *b4b_dwm_slots+232(%rip)\n"
    "b4b_dwm_r129: mov $29, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_130\nb4b_dwm_130: jmp *b4b_dwm_slots+240(%rip)\n"
    "b4b_dwm_r130: mov $30, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_131\nb4b_dwm_131: jmp *b4b_dwm_slots+248(%rip)\n"
    "b4b_dwm_r131: mov $31, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_132\nb4b_dwm_132: jmp *b4b_dwm_slots+256(%rip)\n"
    "b4b_dwm_r132: mov $32, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_133\nb4b_dwm_133: jmp *b4b_dwm_slots+264(%rip)\n"
    "b4b_dwm_r133: mov $33, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_134\nb4b_dwm_134: jmp *b4b_dwm_slots+272(%rip)\n"
    "b4b_dwm_r134: mov $34, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_135\nb4b_dwm_135: jmp *b4b_dwm_slots+280(%rip)\n"
    "b4b_dwm_r135: mov $35, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_136\nb4b_dwm_136: jmp *b4b_dwm_slots+288(%rip)\n"
    "b4b_dwm_r136: mov $36, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_137\nb4b_dwm_137: jmp *b4b_dwm_slots+296(%rip)\n"
    "b4b_dwm_r137: mov $37, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_138\nb4b_dwm_138: jmp *b4b_dwm_slots+304(%rip)\n"
    "b4b_dwm_r138: mov $38, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_139\nb4b_dwm_139: jmp *b4b_dwm_slots+312(%rip)\n"
    "b4b_dwm_r139: mov $39, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_140\nb4b_dwm_140: jmp *b4b_dwm_slots+320(%rip)\n"
    "b4b_dwm_r140: mov $40, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_141\nb4b_dwm_141: jmp *b4b_dwm_slots+328(%rip)\n"
    "b4b_dwm_r141: mov $41, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_142\nb4b_dwm_142: jmp *b4b_dwm_slots+336(%rip)\n"
    "b4b_dwm_r142: mov $42, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_143\nb4b_dwm_143: jmp *b4b_dwm_slots+344(%rip)\n"
    "b4b_dwm_r143: mov $43, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_144\nb4b_dwm_144: jmp *b4b_dwm_slots+352(%rip)\n"
    "b4b_dwm_r144: mov $44, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_145\nb4b_dwm_145: jmp *b4b_dwm_slots+360(%rip)\n"
    "b4b_dwm_r145: mov $45, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_146\nb4b_dwm_146: jmp *b4b_dwm_slots+368(%rip)\n"
    "b4b_dwm_r146: mov $46, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_147\nb4b_dwm_147: jmp *b4b_dwm_slots+376(%rip)\n"
    "b4b_dwm_r147: mov $47, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_148\nb4b_dwm_148: jmp *b4b_dwm_slots+384(%rip)\n"
    "b4b_dwm_r148: mov $48, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_149\nb4b_dwm_149: jmp *b4b_dwm_slots+392(%rip)\n"
    "b4b_dwm_r149: mov $49, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_150\nb4b_dwm_150: jmp *b4b_dwm_slots+400(%rip)\n"
    "b4b_dwm_r150: mov $50, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_151\nb4b_dwm_151: jmp *b4b_dwm_slots+408(%rip)\n"
    "b4b_dwm_r151: mov $51, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_152\nb4b_dwm_152: jmp *b4b_dwm_slots+416(%rip)\n"
    "b4b_dwm_r152: mov $52, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_153\nb4b_dwm_153: jmp *b4b_dwm_slots+424(%rip)\n"
    "b4b_dwm_r153: mov $53, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_154\nb4b_dwm_154: jmp *b4b_dwm_slots+432(%rip)\n"
    "b4b_dwm_r154: mov $54, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_155\nb4b_dwm_155: jmp *b4b_dwm_slots+440(%rip)\n"
    "b4b_dwm_r155: mov $55, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_156\nb4b_dwm_156: jmp *b4b_dwm_slots+448(%rip)\n"
    "b4b_dwm_r156: mov $56, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_157\nb4b_dwm_157: jmp *b4b_dwm_slots+456(%rip)\n"
    "b4b_dwm_r157: mov $57, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_158\nb4b_dwm_158: jmp *b4b_dwm_slots+464(%rip)\n"
    "b4b_dwm_r158: mov $58, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_159\nb4b_dwm_159: jmp *b4b_dwm_slots+472(%rip)\n"
    "b4b_dwm_r159: mov $59, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_160\nb4b_dwm_160: jmp *b4b_dwm_slots+480(%rip)\n"
    "b4b_dwm_r160: mov $60, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_161\nb4b_dwm_161: jmp *b4b_dwm_slots+488(%rip)\n"
    "b4b_dwm_r161: mov $61, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_162\nb4b_dwm_162: jmp *b4b_dwm_slots+496(%rip)\n"
    "b4b_dwm_r162: mov $62, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_163\nb4b_dwm_163: jmp *b4b_dwm_slots+504(%rip)\n"
    "b4b_dwm_r163: mov $63, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_164\nb4b_dwm_164: jmp *b4b_dwm_slots+512(%rip)\n"
    "b4b_dwm_r164: mov $64, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_165\nb4b_dwm_165: jmp *b4b_dwm_slots+520(%rip)\n"
    "b4b_dwm_r165: mov $65, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_166\nb4b_dwm_166: jmp *b4b_dwm_slots+528(%rip)\n"
    "b4b_dwm_r166: mov $66, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_167\nb4b_dwm_167: jmp *b4b_dwm_slots+536(%rip)\n"
    "b4b_dwm_r167: mov $67, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_168\nb4b_dwm_168: jmp *b4b_dwm_slots+544(%rip)\n"
    "b4b_dwm_r168: mov $68, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_169\nb4b_dwm_169: jmp *b4b_dwm_slots+552(%rip)\n"
    "b4b_dwm_r169: mov $69, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_170\nb4b_dwm_170: jmp *b4b_dwm_slots+560(%rip)\n"
    "b4b_dwm_r170: mov $70, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_171\nb4b_dwm_171: jmp *b4b_dwm_slots+568(%rip)\n"
    "b4b_dwm_r171: mov $71, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_172\nb4b_dwm_172: jmp *b4b_dwm_slots+576(%rip)\n"
    "b4b_dwm_r172: mov $72, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_173\nb4b_dwm_173: jmp *b4b_dwm_slots+584(%rip)\n"
    "b4b_dwm_r173: mov $73, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_174\nb4b_dwm_174: jmp *b4b_dwm_slots+592(%rip)\n"
    "b4b_dwm_r174: mov $74, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_175\nb4b_dwm_175: jmp *b4b_dwm_slots+600(%rip)\n"
    "b4b_dwm_r175: mov $75, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_176\nb4b_dwm_176: jmp *b4b_dwm_slots+608(%rip)\n"
    "b4b_dwm_r176: mov $76, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_177\nb4b_dwm_177: jmp *b4b_dwm_slots+616(%rip)\n"
    "b4b_dwm_r177: mov $77, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_178\nb4b_dwm_178: jmp *b4b_dwm_slots+624(%rip)\n"
    "b4b_dwm_r178: mov $78, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_179\nb4b_dwm_179: jmp *b4b_dwm_slots+632(%rip)\n"
    "b4b_dwm_r179: mov $79, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_180\nb4b_dwm_180: jmp *b4b_dwm_slots+640(%rip)\n"
    "b4b_dwm_r180: mov $80, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_181\nb4b_dwm_181: jmp *b4b_dwm_slots+648(%rip)\n"
    "b4b_dwm_r181: mov $81, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_182\nb4b_dwm_182: jmp *b4b_dwm_slots+656(%rip)\n"
    "b4b_dwm_r182: mov $82, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_183\nb4b_dwm_183: jmp *b4b_dwm_slots+664(%rip)\n"
    "b4b_dwm_r183: mov $83, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_184\nb4b_dwm_184: jmp *b4b_dwm_slots+672(%rip)\n"
    "b4b_dwm_r184: mov $84, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_185\nb4b_dwm_185: jmp *b4b_dwm_slots+680(%rip)\n"
    "b4b_dwm_r185: mov $85, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_186\nb4b_dwm_186: jmp *b4b_dwm_slots+688(%rip)\n"
    "b4b_dwm_r186: mov $86, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_187\nb4b_dwm_187: jmp *b4b_dwm_slots+696(%rip)\n"
    "b4b_dwm_r187: mov $87, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_188\nb4b_dwm_188: jmp *b4b_dwm_slots+704(%rip)\n"
    "b4b_dwm_r188: mov $88, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_189\nb4b_dwm_189: jmp *b4b_dwm_slots+712(%rip)\n"
    "b4b_dwm_r189: mov $89, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_190\nb4b_dwm_190: jmp *b4b_dwm_slots+720(%rip)\n"
    "b4b_dwm_r190: mov $90, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_191\nb4b_dwm_191: jmp *b4b_dwm_slots+728(%rip)\n"
    "b4b_dwm_r191: mov $91, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_192\nb4b_dwm_192: jmp *b4b_dwm_slots+736(%rip)\n"
    "b4b_dwm_r192: mov $92, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_193\nb4b_dwm_193: jmp *b4b_dwm_slots+744(%rip)\n"
    "b4b_dwm_r193: mov $93, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_194\nb4b_dwm_194: jmp *b4b_dwm_slots+752(%rip)\n"
    "b4b_dwm_r194: mov $94, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_195\nb4b_dwm_195: jmp *b4b_dwm_slots+760(%rip)\n"
    "b4b_dwm_r195: mov $95, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_196\nb4b_dwm_196: jmp *b4b_dwm_slots+768(%rip)\n"
    "b4b_dwm_r196: mov $96, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_197\nb4b_dwm_197: jmp *b4b_dwm_slots+776(%rip)\n"
    "b4b_dwm_r197: mov $97, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_198\nb4b_dwm_198: jmp *b4b_dwm_slots+784(%rip)\n"
    "b4b_dwm_r198: mov $98, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_199\nb4b_dwm_199: jmp *b4b_dwm_slots+792(%rip)\n"
    "b4b_dwm_r199: mov $99, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_200\nb4b_dwm_200: jmp *b4b_dwm_slots+800(%rip)\n"
    "b4b_dwm_r200: mov $100, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_201\nb4b_dwm_201: jmp *b4b_dwm_slots+808(%rip)\n"
    "b4b_dwm_r201: mov $101, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_202\nb4b_dwm_202: jmp *b4b_dwm_slots+816(%rip)\n"
    "b4b_dwm_r202: mov $102, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_203\nb4b_dwm_203: jmp *b4b_dwm_slots+824(%rip)\n"
    "b4b_dwm_r203: mov $103, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_204\nb4b_dwm_204: jmp *b4b_dwm_slots+832(%rip)\n"
    "b4b_dwm_r204: mov $104, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_205\nb4b_dwm_205: jmp *b4b_dwm_slots+840(%rip)\n"
    "b4b_dwm_r205: mov $105, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_206\nb4b_dwm_206: jmp *b4b_dwm_slots+848(%rip)\n"
    "b4b_dwm_r206: mov $106, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_207\nb4b_dwm_207: jmp *b4b_dwm_slots+856(%rip)\n"
    "b4b_dwm_r207: mov $107, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_208\nb4b_dwm_208: jmp *b4b_dwm_slots+864(%rip)\n"
    "b4b_dwm_r208: mov $108, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_209\nb4b_dwm_209: jmp *b4b_dwm_slots+872(%rip)\n"
    "b4b_dwm_r209: mov $109, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_210\nb4b_dwm_210: jmp *b4b_dwm_slots+880(%rip)\n"
    "b4b_dwm_r210: mov $110, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_211\nb4b_dwm_211: jmp *b4b_dwm_slots+888(%rip)\n"
    "b4b_dwm_r211: mov $111, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_212\nb4b_dwm_212: jmp *b4b_dwm_slots+896(%rip)\n"
    "b4b_dwm_r212: mov $112, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_213\nb4b_dwm_213: jmp *b4b_dwm_slots+904(%rip)\n"
    "b4b_dwm_r213: mov $113, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_214\nb4b_dwm_214: jmp *b4b_dwm_slots+912(%rip)\n"
    "b4b_dwm_r214: mov $114, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_215\nb4b_dwm_215: jmp *b4b_dwm_slots+920(%rip)\n"
    "b4b_dwm_r215: mov $115, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_216\nb4b_dwm_216: jmp *b4b_dwm_slots+928(%rip)\n"
    "b4b_dwm_r216: mov $116, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_217\nb4b_dwm_217: jmp *b4b_dwm_slots+936(%rip)\n"
    "b4b_dwm_r217: mov $117, %eax\n  jmp b4b_dwm_common\n"
    ".globl b4b_dwm_218\nb4b_dwm_218: jmp *b4b_dwm_slots+944(%rip)\n"
    "b4b_dwm_r218: mov $118, %eax\n  jmp b4b_dwm_common\n"
    ".data\n  .balign 8\n"
    ".globl b4b_dwm_slots\nb4b_dwm_slots:\n"
    "  .quad b4b_dwm_r100\n"
    "  .quad b4b_dwm_r101\n"
    "  .quad b4b_dwm_r102\n"
    "  .quad b4b_dwm_r103\n"
    "  .quad b4b_dwm_r104\n"
    "  .quad b4b_dwm_r105\n"
    "  .quad b4b_dwm_r106\n"
    "  .quad b4b_dwm_r107\n"
    "  .quad b4b_dwm_r108\n"
    "  .quad b4b_dwm_r109\n"
    "  .quad b4b_dwm_r110\n"
    "  .quad b4b_dwm_r111\n"
    "  .quad b4b_dwm_r112\n"
    "  .quad b4b_dwm_r113\n"
    "  .quad b4b_dwm_r114\n"
    "  .quad b4b_dwm_r115\n"
    "  .quad b4b_dwm_r116\n"
    "  .quad b4b_dwm_r117\n"
    "  .quad b4b_dwm_r118\n"
    "  .quad b4b_dwm_r119\n"
    "  .quad b4b_dwm_r120\n"
    "  .quad b4b_dwm_r121\n"
    "  .quad b4b_dwm_r122\n"
    "  .quad b4b_dwm_r123\n"
    "  .quad b4b_dwm_r124\n"
    "  .quad b4b_dwm_r125\n"
    "  .quad b4b_dwm_r126\n"
    "  .quad b4b_dwm_r127\n"
    "  .quad b4b_dwm_r128\n"
    "  .quad b4b_dwm_r129\n"
    "  .quad b4b_dwm_r130\n"
    "  .quad b4b_dwm_r131\n"
    "  .quad b4b_dwm_r132\n"
    "  .quad b4b_dwm_r133\n"
    "  .quad b4b_dwm_r134\n"
    "  .quad b4b_dwm_r135\n"
    "  .quad b4b_dwm_r136\n"
    "  .quad b4b_dwm_r137\n"
    "  .quad b4b_dwm_r138\n"
    "  .quad b4b_dwm_r139\n"
    "  .quad b4b_dwm_r140\n"
    "  .quad b4b_dwm_r141\n"
    "  .quad b4b_dwm_r142\n"
    "  .quad b4b_dwm_r143\n"
    "  .quad b4b_dwm_r144\n"
    "  .quad b4b_dwm_r145\n"
    "  .quad b4b_dwm_r146\n"
    "  .quad b4b_dwm_r147\n"
    "  .quad b4b_dwm_r148\n"
    "  .quad b4b_dwm_r149\n"
    "  .quad b4b_dwm_r150\n"
    "  .quad b4b_dwm_r151\n"
    "  .quad b4b_dwm_r152\n"
    "  .quad b4b_dwm_r153\n"
    "  .quad b4b_dwm_r154\n"
    "  .quad b4b_dwm_r155\n"
    "  .quad b4b_dwm_r156\n"
    "  .quad b4b_dwm_r157\n"
    "  .quad b4b_dwm_r158\n"
    "  .quad b4b_dwm_r159\n"
    "  .quad b4b_dwm_r160\n"
    "  .quad b4b_dwm_r161\n"
    "  .quad b4b_dwm_r162\n"
    "  .quad b4b_dwm_r163\n"
    "  .quad b4b_dwm_r164\n"
    "  .quad b4b_dwm_r165\n"
    "  .quad b4b_dwm_r166\n"
    "  .quad b4b_dwm_r167\n"
    "  .quad b4b_dwm_r168\n"
    "  .quad b4b_dwm_r169\n"
    "  .quad b4b_dwm_r170\n"
    "  .quad b4b_dwm_r171\n"
    "  .quad b4b_dwm_r172\n"
    "  .quad b4b_dwm_r173\n"
    "  .quad b4b_dwm_r174\n"
    "  .quad b4b_dwm_r175\n"
    "  .quad b4b_dwm_r176\n"
    "  .quad b4b_dwm_r177\n"
    "  .quad b4b_dwm_r178\n"
    "  .quad b4b_dwm_r179\n"
    "  .quad b4b_dwm_r180\n"
    "  .quad b4b_dwm_r181\n"
    "  .quad b4b_dwm_r182\n"
    "  .quad b4b_dwm_r183\n"
    "  .quad b4b_dwm_r184\n"
    "  .quad b4b_dwm_r185\n"
    "  .quad b4b_dwm_r186\n"
    "  .quad b4b_dwm_r187\n"
    "  .quad b4b_dwm_r188\n"
    "  .quad b4b_dwm_r189\n"
    "  .quad b4b_dwm_r190\n"
    "  .quad b4b_dwm_r191\n"
    "  .quad b4b_dwm_r192\n"
    "  .quad b4b_dwm_r193\n"
    "  .quad b4b_dwm_r194\n"
    "  .quad b4b_dwm_r195\n"
    "  .quad b4b_dwm_r196\n"
    "  .quad b4b_dwm_r197\n"
    "  .quad b4b_dwm_r198\n"
    "  .quad b4b_dwm_r199\n"
    "  .quad b4b_dwm_r200\n"
    "  .quad b4b_dwm_r201\n"
    "  .quad b4b_dwm_r202\n"
    "  .quad b4b_dwm_r203\n"
    "  .quad b4b_dwm_r204\n"
    "  .quad b4b_dwm_r205\n"
    "  .quad b4b_dwm_r206\n"
    "  .quad b4b_dwm_r207\n"
    "  .quad b4b_dwm_r208\n"
    "  .quad b4b_dwm_r209\n"
    "  .quad b4b_dwm_r210\n"
    "  .quad b4b_dwm_r211\n"
    "  .quad b4b_dwm_r212\n"
    "  .quad b4b_dwm_r213\n"
    "  .quad b4b_dwm_r214\n"
    "  .quad b4b_dwm_r215\n"
    "  .quad b4b_dwm_r216\n"
    "  .quad b4b_dwm_r217\n"
    "  .quad b4b_dwm_r218\n"
    ".text\n");
