#!/usr/bin/env python3
"""Generate a proxy for a system DLL (native/proxy/<name>.c + native/proxy/<name>.def).

Every export of the real DLL, named and ordinal-only, is re-exported at the same ordinal and forwarded to the real
DLL in the system directory. On Windows the system d3d/dxgi DLLs resolve dwmapi from the game directory too and
import some ordinal-only functions, so a proxy with only the named exports the game uses fails to load ("The ordinal
N could not be located"); the same rule is kept for every proxied name.
Usage: gen-proxy.py <real.dll | existing proxy .def> [name]
  gen-proxy.py C:/Windows/System32/dwmapi.dll
  gen-proxy.py <prefix>/drive_c/windows/system32/x3daudio1_7.dll X3DAudio1_7.dll   (native MS file from the DX redist)
  gen-proxy.py native/proxy/dwmapi.def dwmapi.dll   (regenerate from the export list of an earlier run)
The name (default: the source's file name) is the file the proxy is loaded as, and the file loaded from the system
directory for the real functions.
"""
import os, re, struct, sys

def exports(path):
    d = open(path, 'rb').read()
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    nsec, = struct.unpack_from('<H', d, pe + 6)
    osz, = struct.unpack_from('<H', d, pe + 20)
    opt = pe + 24
    erva, = struct.unpack_from('<I', d, opt + 112)
    secs = [struct.unpack_from('<8sIIII', d, opt + osz + i * 40) for i in range(nsec)]
    def off(rva):
        for _, vs, va, rs, ro in secs:
            if va <= rva < va + max(vs, rs): return rva - va + ro
        raise ValueError(hex(rva))
    e = off(erva)
    base, nf, nn, af, anames, aords = struct.unpack_from('<IIIIII', d, e + 16)
    names = {}
    for i in range(nn):
        no, = struct.unpack_from('<I', d, off(anames) + 4 * i)
        o, = struct.unpack_from('<H', d, off(aords) + 2 * i)
        names[o] = d[off(no):d.index(b'\0', off(no))].decode()
    return [(base + i, names.get(i)) for i in range(nf) if struct.unpack_from('<I', d, off(af) + 4 * i)[0]]

def def_exports(path):
    """Export list of a .def this script wrote earlier."""
    out = []
    for line in open(path):
        m = re.match(r'\s+(?:(\S+)=)?\S+ @(\d+)( NONAME)?\s*$', line)
        if m: out.append((int(m.group(2)), None if m.group(3) else m.group(1)))
    return out

def main():
    if len(sys.argv) < 2: sys.exit(__doc__)
    src = sys.argv[1]
    name = sys.argv[2] if len(sys.argv) > 2 else os.path.basename(src)
    if not name.lower().endswith('.dll'): name += '.dll'
    ex = def_exports(src) if src.lower().endswith('.def') else exports(src)
    stem = name[:-4]
    base = stem.lower()
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'native', 'proxy')
    os.makedirs(root, exist_ok=True)
    n = len(ex)
    c = [f'''// GENERATED by tools/gen-proxy.py -- do not edit.
// {name} proxy: re-exports all {n} exports of the real system {name} (ordinals in native/proxy/{base}.def).
// Each export is `jmp *slot`; a slot starts at a resolver thunk that looks up the real function on first call
// (by name, or by ordinal for unnamed exports), so nothing is loaded under the loader lock.
#include <windows.h>

#define NPROXY {n}
static const char *const names[NPROXY] = {{''']
    c += [f'    {"\"" + nm + "\"" if nm else "0"},  // @{o}' for o, nm in ex]
    c.append('};\nstatic const unsigned short ords[NPROXY] = {')
    c.append('    ' + ', '.join(str(o) for o, _ in ex))
    c.append('};')
    c.append('extern void *b4b_px_slots[NPROXY];')
    c.append(f'''
const wchar_t b4b_proxy_name[] = L"{name}";   // the name this DLL is installed as
static HMODULE real;
static HRESULT WINAPI not_impl(void) {{ return E_NOTIMPL; }}

void *b4b_px_resolve(unsigned i) {{
    if (!real) {{
        wchar_t path[MAX_PATH];
        GetSystemDirectoryW(path, MAX_PATH);
        lstrcatW(path, L"\\\\{name}");
        real = LoadLibraryW(path);
    }}
    void *f = real ? (void *)GetProcAddress(real, names[i] ? names[i] : MAKEINTRESOURCEA(ords[i])) : 0;
    if (!f) f = (void *)not_impl;
    b4b_px_slots[i] = f;
    return f;
}}

// Resolver entry: eax = slot index. Preserves the Win64 argument registers, then tail-jumps to the target.
__asm__(
    ".text\\n"
    "b4b_px_common:\\n"
    "  push %rcx\\n  push %rdx\\n  push %r8\\n  push %r9\\n"
    "  sub $0x68, %rsp\\n"
    "  movdqu %xmm0, 0x20(%rsp)\\n  movdqu %xmm1, 0x30(%rsp)\\n"
    "  movdqu %xmm2, 0x40(%rsp)\\n  movdqu %xmm3, 0x50(%rsp)\\n"
    "  mov %eax, %ecx\\n"
    "  call b4b_px_resolve\\n"
    "  movdqu 0x20(%rsp), %xmm0\\n  movdqu 0x30(%rsp), %xmm1\\n"
    "  movdqu 0x40(%rsp), %xmm2\\n  movdqu 0x50(%rsp), %xmm3\\n"
    "  add $0x68, %rsp\\n"
    "  pop %r9\\n  pop %r8\\n  pop %rdx\\n  pop %rcx\\n"
    "  jmp *%rax\\n"''')
    for i, (o, _) in enumerate(ex):
        c.append(f'    ".globl b4b_px_{o}\\nb4b_px_{o}: jmp *b4b_px_slots+{8 * i}(%rip)\\n"')
        c.append(f'    "b4b_px_r{o}: mov ${i}, %eax\\n  jmp b4b_px_common\\n"')
    c.append('    ".data\\n  .balign 8\\n"')
    c.append('    ".globl b4b_px_slots\\nb4b_px_slots:\\n"')
    for o, _ in ex:
        c.append(f'    "  .quad b4b_px_r{o}\\n"')
    c.append('    ".text\\n");\n')
    open(os.path.join(root, base + '.c'), 'w', newline='\n').write('\n'.join(c))
    d = ['; GENERATED by tools/gen-proxy.py -- do not edit.', f'LIBRARY {stem}', 'EXPORTS']
    d += [f'    {nm}=b4b_px_{o} @{o}' if nm else f'    b4b_px_{o} @{o} NONAME' for o, nm in ex]
    open(os.path.join(root, base + '.def'), 'w', newline='\n').write('\n'.join(d) + '\n')
    print(f'{n} exports from {src} -> native/proxy/{base}.c, {base}.def')

main()
