#!/usr/bin/env python3
"""Generate the dwmapi.dll proxy (native/src/proxy.c + native/dwmapi.def) from a real dwmapi.dll.

Every export of the real DLL, named and ordinal-only, is re-exported at the same ordinal. On Windows the system
d3d/dxgi DLLs resolve dwmapi from the game directory too and import some ordinal-only functions, so a proxy with
only the named exports the game uses fails to load ("The ordinal N could not be located").
Usage: gen-proxy.py [path/to/dwmapi.dll]   (default: C:/Windows/System32/dwmapi.dll)
"""
import os, struct, sys

def exports(path):
    d = open(path, 'rb').read()
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    nsec, = struct.unpack_from('<H', d, pe + 6)
    osz, = struct.unpack_from('<H', d, pe + 20)
    opt = pe + 24
    erva, = struct.unpack_from('<I', d, opt + 112)
    secs = [struct.unpack_from('<8sIIII', d, opt + osz + i * 40) for i in range(nsec)]
    def off(rva):
        for _, vs, va, rs, ro in secs:
            if va <= rva < va + max(vs, rs): return rva - va + ro
        raise ValueError(hex(rva))
    e = off(erva)
    base, nf, nn, af, anames, aords = struct.unpack_from('<IIIIII', d, e + 16)
    names = {}
    for i in range(nn):
        no, = struct.unpack_from('<I', d, off(anames) + 4 * i)
        o, = struct.unpack_from('<H', d, off(aords) + 2 * i)
        names[o] = d[off(no):d.index(b'\0', off(no))].decode()
    return [(base + i, names.get(i)) for i in range(nf) if struct.unpack_from('<I', d, off(af) + 4 * i)[0]]

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'C:/Windows/System32/dwmapi.dll'
    ex = exports(src)
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'native')
    n = len(ex)
    c = [f'''// GENERATED by tools/gen-proxy.py -- do not edit.
// dwmapi.dll proxy: re-exports all {n} exports of the real system dwmapi (ordinals in native/dwmapi.def).
// Each export is `jmp *slot`; a slot starts at a resolver thunk that looks up the real function on first call
// (by name, or by ordinal for unnamed exports), so nothing is loaded under the loader lock.
#include <windows.h>

#define NPROXY {n}
static const char *const names[NPROXY] = {{''']
    c += [f'    {"\"" + nm + "\"" if nm else "0"},  // @{o}' for o, nm in ex]
    c.append('};\nstatic const unsigned short ords[NPROXY] = {')
    c.append('    ' + ', '.join(str(o) for o, _ in ex))
    c.append('};')
    c.append('extern void *b4b_dwm_slots[NPROXY];')
    c.append('''
static HMODULE real;
static HRESULT WINAPI not_impl(void) { return E_NOTIMPL; }

void *b4b_dwm_resolve(unsigned i) {
    if (!real) {
        wchar_t path[MAX_PATH];
        GetSystemDirectoryW(path, MAX_PATH);
        lstrcatW(path, L"\\\\dwmapi.dll");
        real = LoadLibraryW(path);
    }
    void *f = real ? (void *)GetProcAddress(real, names[i] ? names[i] : MAKEINTRESOURCEA(ords[i])) : 0;
    if (!f) f = (void *)not_impl;
    b4b_dwm_slots[i] = f;
    return f;
}

// Resolver entry: eax = slot index. Preserves the Win64 argument registers, then tail-jumps to the target.
__asm__(
    ".text\\n"
    "b4b_dwm_common:\\n"
    "  push %rcx\\n  push %rdx\\n  push %r8\\n  push %r9\\n"
    "  sub $0x68, %rsp\\n"
    "  movdqu %xmm0, 0x20(%rsp)\\n  movdqu %xmm1, 0x30(%rsp)\\n"
    "  movdqu %xmm2, 0x40(%rsp)\\n  movdqu %xmm3, 0x50(%rsp)\\n"
    "  mov %eax, %ecx\\n"
    "  call b4b_dwm_resolve\\n"
    "  movdqu 0x20(%rsp), %xmm0\\n  movdqu 0x30(%rsp), %xmm1\\n"
    "  movdqu 0x40(%rsp), %xmm2\\n  movdqu 0x50(%rsp), %xmm3\\n"
    "  add $0x68, %rsp\\n"
    "  pop %r9\\n  pop %r8\\n  pop %rdx\\n  pop %rcx\\n"
    "  jmp *%rax\\n"''')
    for i, (o, _) in enumerate(ex):
        c.append(f'    ".globl b4b_dwm_{o}\\nb4b_dwm_{o}: jmp *b4b_dwm_slots+{8 * i}(%rip)\\n"')
        c.append(f'    "b4b_dwm_r{o}: mov ${i}, %eax\\n  jmp b4b_dwm_common\\n"')
    c.append('    ".data\\n  .balign 8\\n"')
    c.append('    ".globl b4b_dwm_slots\\nb4b_dwm_slots:\\n"')
    for o, _ in ex:
        c.append(f'    "  .quad b4b_dwm_r{o}\\n"')
    c.append('    ".text\\n");\n')
    open(os.path.join(root, 'src', 'proxy.c'), 'w', newline='\n').write('\n'.join(c))
    d = ['; GENERATED by tools/gen-proxy.py -- do not edit.', 'LIBRARY dwmapi', 'EXPORTS']
    d += [f'    {nm}=b4b_dwm_{o} @{o}' if nm else f'    b4b_dwm_{o} @{o} NONAME' for o, nm in ex]
    open(os.path.join(root, 'dwmapi.def'), 'w', newline='\n').write('\n'.join(d) + '\n')
    print(f'{n} exports from {src}')

main()
