// GENERATED by tools/gen-proxy.py -- do not edit.
// X3DAudio1_7.dll proxy: re-exports all 2 exports of the real system X3DAudio1_7.dll (ordinals in native/proxy/x3daudio1_7.def).
// Each export is `jmp *slot`; a slot starts at a resolver thunk that looks up the real function on first call
// (by name, or by ordinal for unnamed exports), so nothing is loaded under the loader lock.
#include <windows.h>

#define NPROXY 2
static const char *const names[NPROXY] = {
    "X3DAudioCalculate",  // @1
    "X3DAudioInitialize",  // @2
};
static const unsigned short ords[NPROXY] = {
    1, 2
};
extern void *b4b_px_slots[NPROXY];

const wchar_t b4b_proxy_name[] = L"X3DAudio1_7.dll";   // the name this DLL is installed as
static HMODULE real;
static HRESULT WINAPI not_impl(void) { return E_NOTIMPL; }

void *b4b_px_resolve(unsigned i) {
    if (!real) {
        wchar_t path[MAX_PATH];
        GetSystemDirectoryW(path, MAX_PATH);
        lstrcatW(path, L"\\X3DAudio1_7.dll");
        real = LoadLibraryW(path);
    }
    void *f = real ? (void *)GetProcAddress(real, names[i] ? names[i] : MAKEINTRESOURCEA(ords[i])) : 0;
    if (!f) f = (void *)not_impl;
    b4b_px_slots[i] = f;
    return f;
}

// Resolver entry: eax = slot index. Preserves the Win64 argument registers, then tail-jumps to the target.
__asm__(
    ".text\n"
    "b4b_px_common:\n"
    "  push %rcx\n  push %rdx\n  push %r8\n  push %r9\n"
    "  sub $0x68, %rsp\n"
    "  movdqu %xmm0, 0x20(%rsp)\n  movdqu %xmm1, 0x30(%rsp)\n"
    "  movdqu %xmm2, 0x40(%rsp)\n  movdqu %xmm3, 0x50(%rsp)\n"
    "  mov %eax, %ecx\n"
    "  call b4b_px_resolve\n"
    "  movdqu 0x20(%rsp), %xmm0\n  movdqu 0x30(%rsp), %xmm1\n"
    "  movdqu 0x40(%rsp), %xmm2\n  movdqu 0x50(%rsp), %xmm3\n"
    "  add $0x68, %rsp\n"
    "  pop %r9\n  pop %r8\n  pop %rdx\n  pop %rcx\n"
    "  jmp *%rax\n"
    ".globl b4b_px_1\nb4b_px_1: jmp *b4b_px_slots+0(%rip)\n"
    "b4b_px_r1: mov $0, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_2\nb4b_px_2: jmp *b4b_px_slots+8(%rip)\n"
    "b4b_px_r2: mov $1, %eax\n  jmp b4b_px_common\n"
    ".data\n  .balign 8\n"
    ".globl b4b_px_slots\nb4b_px_slots:\n"
    "  .quad b4b_px_r1\n"
    "  .quad b4b_px_r2\n"
    ".text\n");
