// GENERATED by tools/gen-proxy.py -- do not edit.
// xinput1_3.dll proxy: re-exports all 12 exports of the real system xinput1_3.dll (ordinals in native/proxy/xinput1_3.def).
// Each export is `jmp *slot`; a slot starts at a resolver thunk that looks up the real function on first call
// (by name, or by ordinal for unnamed exports), so nothing is loaded under the loader lock.
#include <windows.h>

#define NPROXY 12
static const char *const names[NPROXY] = {
    "DllMain",  // @1
    "XInputGetState",  // @2
    "XInputSetState",  // @3
    "XInputGetCapabilities",  // @4
    "XInputEnable",  // @5
    "XInputGetDSoundAudioDeviceGuids",  // @6
    "XInputGetBatteryInformation",  // @7
    "XInputGetKeystroke",  // @8
    0,  // @100
    0,  // @101
    0,  // @102
    0,  // @103
};
static const unsigned short ords[NPROXY] = {
    1, 2, 3, 4, 5, 6, 7, 8, 100, 101, 102, 103
};
extern void *b4b_px_slots[NPROXY];

const wchar_t b4b_proxy_name[] = L"xinput1_3.dll";   // the name this DLL is installed as
static HMODULE real;
static HRESULT WINAPI not_impl(void) { return E_NOTIMPL; }

void *b4b_px_resolve(unsigned i) {
    if (!real) {
        wchar_t path[MAX_PATH];
        GetSystemDirectoryW(path, MAX_PATH);
        lstrcatW(path, L"\\xinput1_3.dll");
        real = LoadLibraryW(path);
    }
    void *f = real ? (void *)GetProcAddress(real, names[i] ? names[i] : MAKEINTRESOURCEA(ords[i])) : 0;
    if (!f) f = (void *)not_impl;
    b4b_px_slots[i] = f;
    return f;
}

// Resolver entry: eax = slot index. Preserves the Win64 argument registers, then tail-jumps to the target.
__asm__(
    ".text\n"
    "b4b_px_common:\n"
    "  push %rcx\n  push %rdx\n  push %r8\n  push %r9\n"
    "  sub $0x68, %rsp\n"
    "  movdqu %xmm0, 0x20(%rsp)\n  movdqu %xmm1, 0x30(%rsp)\n"
    "  movdqu %xmm2, 0x40(%rsp)\n  movdqu %xmm3, 0x50(%rsp)\n"
    "  mov %eax, %ecx\n"
    "  call b4b_px_resolve\n"
    "  movdqu 0x20(%rsp), %xmm0\n  movdqu 0x30(%rsp), %xmm1\n"
    "  movdqu 0x40(%rsp), %xmm2\n  movdqu 0x50(%rsp), %xmm3\n"
    "  add $0x68, %rsp\n"
    "  pop %r9\n  pop %r8\n  pop %rdx\n  pop %rcx\n"
    "  jmp *%rax\n"
    ".globl b4b_px_1\nb4b_px_1: jmp *b4b_px_slots+0(%rip)\n"
    "b4b_px_r1: mov $0, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_2\nb4b_px_2: jmp *b4b_px_slots+8(%rip)\n"
    "b4b_px_r2: mov $1, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_3\nb4b_px_3: jmp *b4b_px_slots+16(%rip)\n"
    "b4b_px_r3: mov $2, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_4\nb4b_px_4: jmp *b4b_px_slots+24(%rip)\n"
    "b4b_px_r4: mov $3, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_5\nb4b_px_5: jmp *b4b_px_slots+32(%rip)\n"
    "b4b_px_r5: mov $4, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_6\nb4b_px_6: jmp *b4b_px_slots+40(%rip)\n"
    "b4b_px_r6: mov $5, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_7\nb4b_px_7: jmp *b4b_px_slots+48(%rip)\n"
    "b4b_px_r7: mov $6, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_8\nb4b_px_8: jmp *b4b_px_slots+56(%rip)\n"
    "b4b_px_r8: mov $7, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_100\nb4b_px_100: jmp *b4b_px_slots+64(%rip)\n"
    "b4b_px_r100: mov $8, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_101\nb4b_px_101: jmp *b4b_px_slots+72(%rip)\n"
    "b4b_px_r101: mov $9, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_102\nb4b_px_102: jmp *b4b_px_slots+80(%rip)\n"
    "b4b_px_r102: mov $10, %eax\n  jmp b4b_px_common\n"
    ".globl b4b_px_103\nb4b_px_103: jmp *b4b_px_slots+88(%rip)\n"
    "b4b_px_r103: mov $11, %eax\n  jmp b4b_px_common\n"
    ".data\n  .balign 8\n"
    ".globl b4b_px_slots\nb4b_px_slots:\n"
    "  .quad b4b_px_r1\n"
    "  .quad b4b_px_r2\n"
    "  .quad b4b_px_r3\n"
    "  .quad b4b_px_r4\n"
    "  .quad b4b_px_r5\n"
    "  .quad b4b_px_r6\n"
    "  .quad b4b_px_r7\n"
    "  .quad b4b_px_r8\n"
    "  .quad b4b_px_r100\n"
    "  .quad b4b_px_r101\n"
    "  .quad b4b_px_r102\n"
    "  .quad b4b_px_r103\n"
    ".text\n");
